# This file was generated automatically from conda-smithy. To update this configuration,
# update the conda-forge.yml and/or the recipe/meta.yaml.

language: shell



jobs:
  include:
    - env: CONFIG=linux_aarch64_python_abi_tagcp310python_impl_version3.10python_implementationcpythonpython_version3.10 UPLOAD_PACKAGES=True PLATFORM=linux-aarch64 DOCKER_IMAGE=quay.io/condaforge/linux-anvil-aarch64
      os: linux
      arch: arm64
      dist: focal

    - env: CONFIG=linux_aarch64_python_abi_tagcp311python_impl_version3.11python_implementationcpythonpython_version3.11 UPLOAD_PACKAGES=True PLATFORM=linux-aarch64 DOCKER_IMAGE=quay.io/condaforge/linux-anvil-aarch64
      os: linux
      arch: arm64
      dist: focal

    - env: CONFIG=linux_aarch64_python_abi_tagcp312python_impl_version3.12python_implementationcpythonpython_version3.12 UPLOAD_PACKAGES=True PLATFORM=linux-aarch64 DOCKER_IMAGE=quay.io/condaforge/linux-anvil-aarch64
      os: linux
      arch: arm64
      dist: focal

    - env: CONFIG=linux_aarch64_python_abi_tagcp313python_impl_version3.13python_implementationcpythonpython_version3.13 UPLOAD_PACKAGES=True PLATFORM=linux-aarch64 DOCKER_IMAGE=quay.io/condaforge/linux-anvil-aarch64
      os: linux
      arch: arm64
      dist: focal

    - env: CONFIG=linux_aarch64_python_abi_tagcp313tpython_impl_version3.13python_implementationcpythonpython_version3.13 UPLOAD_PACKAGES=True PLATFORM=linux-aarch64 DOCKER_IMAGE=quay.io/condaforge/linux-anvil-aarch64
      os: linux
      arch: arm64
      dist: focal

    - env: CONFIG=linux_aarch64_python_abi_tagcp37mpython_impl_version3.7python_implementationcpythonpython_version3.7 UPLOAD_PACKAGES=True PLATFORM=linux-aarch64 DOCKER_IMAGE=quay.io/condaforge/linux-anvil-aarch64
      os: linux
      arch: arm64
      dist: focal

    - env: CONFIG=linux_aarch64_python_abi_tagcp38python_impl_version3.8python_implementationcpythonpython_version3.8 UPLOAD_PACKAGES=True PLATFORM=linux-aarch64 DOCKER_IMAGE=quay.io/condaforge/linux-anvil-aarch64
      os: linux
      arch: arm64
      dist: focal

    - env: CONFIG=linux_aarch64_python_abi_tagcp39python_impl_version3.9python_implementationcpythonpython_version3.9 UPLOAD_PACKAGES=True PLATFORM=linux-aarch64 DOCKER_IMAGE=quay.io/condaforge/linux-anvil-aarch64
      os: linux
      arch: arm64
      dist: focal

    - env: CONFIG=linux_aarch64_python_abi_taggraalpy230_310_nativepython_impl_version23.0python_implementationgraalpypython_version3.10 UPLOAD_PACKAGES=True PLATFORM=linux-aarch64 DOCKER_IMAGE=quay.io/condaforge/linux-anvil-aarch64
      os: linux
      arch: arm64
      dist: focal

    - env: CONFIG=linux_aarch64_python_abi_taggraalpy231_310_nativepython_impl_version23.1python_implementationgraalpypython_version3.10 UPLOAD_PACKAGES=True PLATFORM=linux-aarch64 DOCKER_IMAGE=quay.io/condaforge/linux-anvil-aarch64
      os: linux
      arch: arm64
      dist: focal

    - env: CONFIG=linux_aarch64_python_abi_tagpypy38_pp73python_impl_version7.3python_implementationpypypython_version3.8 UPLOAD_PACKAGES=True PLATFORM=linux-aarch64 DOCKER_IMAGE=quay.io/condaforge/linux-anvil-aarch64
      os: linux
      arch: arm64
      dist: focal

    - env: CONFIG=linux_aarch64_python_abi_tagpypy39_pp73python_impl_version7.3python_implementationpypypython_version3.9 UPLOAD_PACKAGES=True PLATFORM=linux-aarch64 DOCKER_IMAGE=quay.io/condaforge/linux-anvil-aarch64
      os: linux
      arch: arm64
      dist: focal

    - env: CONFIG=linux_ppc64le_python_abi_tagcp310python_impl_version3.10python_implementationcpythonpython_version3.10 UPLOAD_PACKAGES=True PLATFORM=linux-ppc64le DOCKER_IMAGE=quay.io/condaforge/linux-anvil-ppc64le
      os: linux
      arch: ppc64le
      dist: focal

    - env: CONFIG=linux_ppc64le_python_abi_tagcp311python_impl_version3.11python_implementationcpythonpython_version3.11 UPLOAD_PACKAGES=True PLATFORM=linux-ppc64le DOCKER_IMAGE=quay.io/condaforge/linux-anvil-ppc64le
      os: linux
      arch: ppc64le
      dist: focal

    - env: CONFIG=linux_ppc64le_python_abi_tagcp312python_impl_version3.12python_implementationcpythonpython_version3.12 UPLOAD_PACKAGES=True PLATFORM=linux-ppc64le DOCKER_IMAGE=quay.io/condaforge/linux-anvil-ppc64le
      os: linux
      arch: ppc64le
      dist: focal

    - env: CONFIG=linux_ppc64le_python_abi_tagcp313python_impl_version3.13python_implementationcpythonpython_version3.13 UPLOAD_PACKAGES=True PLATFORM=linux-ppc64le DOCKER_IMAGE=quay.io/condaforge/linux-anvil-ppc64le
      os: linux
      arch: ppc64le
      dist: focal

    - env: CONFIG=linux_ppc64le_python_abi_tagcp313tpython_impl_version3.13python_implementationcpythonpython_version3.13 UPLOAD_PACKAGES=True PLATFORM=linux-ppc64le DOCKER_IMAGE=quay.io/condaforge/linux-anvil-ppc64le
      os: linux
      arch: ppc64le
      dist: focal

    - env: CONFIG=linux_ppc64le_python_abi_tagcp37mpython_impl_version3.7python_implementationcpythonpython_version3.7 UPLOAD_PACKAGES=True PLATFORM=linux-ppc64le DOCKER_IMAGE=quay.io/condaforge/linux-anvil-ppc64le
      os: linux
      arch: ppc64le
      dist: focal

    - env: CONFIG=linux_ppc64le_python_abi_tagcp38python_impl_version3.8python_implementationcpythonpython_version3.8 UPLOAD_PACKAGES=True PLATFORM=linux-ppc64le DOCKER_IMAGE=quay.io/condaforge/linux-anvil-ppc64le
      os: linux
      arch: ppc64le
      dist: focal

    - env: CONFIG=linux_ppc64le_python_abi_tagcp39python_impl_version3.9python_implementationcpythonpython_version3.9 UPLOAD_PACKAGES=True PLATFORM=linux-ppc64le DOCKER_IMAGE=quay.io/condaforge/linux-anvil-ppc64le
      os: linux
      arch: ppc64le
      dist: focal

    - env: CONFIG=linux_ppc64le_python_abi_taggraalpy230_310_nativepython_impl_version23.0python_implementationgraalpypython_version3.10 UPLOAD_PACKAGES=True PLATFORM=linux-ppc64le DOCKER_IMAGE=quay.io/condaforge/linux-anvil-ppc64le
      os: linux
      arch: ppc64le
      dist: focal

    - env: CONFIG=linux_ppc64le_python_abi_taggraalpy231_310_nativepython_impl_version23.1python_implementationgraalpypython_version3.10 UPLOAD_PACKAGES=True PLATFORM=linux-ppc64le DOCKER_IMAGE=quay.io/condaforge/linux-anvil-ppc64le
      os: linux
      arch: ppc64le
      dist: focal

    - env: CONFIG=linux_ppc64le_python_abi_tagpypy38_pp73python_impl_version7.3python_implementationpypypython_version3.8 UPLOAD_PACKAGES=True PLATFORM=linux-ppc64le DOCKER_IMAGE=quay.io/condaforge/linux-anvil-ppc64le
      os: linux
      arch: ppc64le
      dist: focal

    - env: CONFIG=linux_ppc64le_python_abi_tagpypy39_pp73python_impl_version7.3python_implementationpypypython_version3.9 UPLOAD_PACKAGES=True PLATFORM=linux-ppc64le DOCKER_IMAGE=quay.io/condaforge/linux-anvil-ppc64le
      os: linux
      arch: ppc64le
      dist: focal

script:
  - export CI=travis
  - export GIT_BRANCH="$TRAVIS_BRANCH"
  - export flow_run_id="travis_$TRAVIS_JOB_ID"
  - export sha="$TRAVIS_COMMIT"
  - export remote_url="https://github.com/$TRAVIS_REPO_SLUG"
  - export FEEDSTOCK_NAME=$(basename ${TRAVIS_REPO_SLUG})
  - if [[ "${TRAVIS_PULL_REQUEST:-}" == "false" ]]; then export IS_PR_BUILD="False"; else export IS_PR_BUILD="True"; fi


  - if [[ ${PLATFORM} =~ .*linux.* ]]; then CONDA_FORGE_DOCKER_RUN_ARGS="--network=host --security-opt=seccomp=unconfined" ./.scripts/run_docker_build.sh; fi